# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'aequilibrium-assessment-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aequilibrium-assessment-ios

  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SwiftSpinner'

  target 'aequilibrium-assessment-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'aequilibrium-assessment-iosUITests' do
    # Pods for testing
  end

end
